### ISSUE TITLE
Completado

### ISSUE THREAD

**Issue by fneria** [fneria/decont#1]
Hola Tomás
Ya he completado el ejercicio. Puedes revisarlo cuando quieras.
Voy a tratar de hacer los bonus exercises. Si lo consigo te cuento y lo revisas tambien

**Comment by tdido** [comment]
Hola Nando.

La solución funciona correctamente. Dos comentarios muy mínimos:

1) Tal como está, pipeline.sh da un error porque estás gestionando el posicionamiento en directorios dentro del script, y como yo tengo nombres de directorios distintos, falla. Como ya tenés correctamente implementado todo usando paths relativos, simplemente es cuestión de eliminar de la línea 2 a la 4.
2) La creación de directorios para cutadapt sería mejor hacerla fuera del loop, ya que son siempre los mismos (no dependen del nombre de muestra).

Cierro esta issue. Si completás el resto de los bonus avisame en otra.
