### ISSUE TITLE
Bonus

### ISSUE THREAD

**Issue by fneria** [fneria/decont#2]
Hola Tomás
He incluido tus sugerencias (¡Muchas gracias!) en mi código y lo he nombrado como pipeline_modif.sh, y sobre este script he incluido codigo para los bonus. Miraló cuando puedas.
Un saludo
Nando

**Comment by tdido** [comment]
Hola Nando.

Perfecto, la solución está completa. Muy buen trabajo.

Simplemente para que lo tengas en cuenta como alternativa, te comento que existe la opción de verificar si un archivo existe mediante `if [ -f "mydir/myfile.tar.gz" ]`.
